### ISSUE TITLE
soapyhackrf build fails when using non-default homebrew prefix

### ISSUE THREAD

**Issue by russm** [pothosware/homebrew-pothos#12]
With homebrew installed at /opt/homebrew, install fails like so:

```
rastapopoulos:~ russm$ sudo -i -u hostadmin brew install --keep-tmp soapyhackrf
Password:
==> Installing soapyhackrf from pothosware/pothos
==> Downloading https://github.com/pothosware/SoapyHackRF/archive/soapy-hackrf-0.3.1.tar.gz
Already downloaded: /Users/hostadmin/Library/Caches/Homebrew/soapyhackrf-0.3.1.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/soapyha
Last 15 lines from /Users/hostadmin/Library/Logs/Homebrew/soapyhackrf/01.cmake:
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working CXX compiler: /opt/homebrew/Library/Homebrew/shims/super/clang++
-- Check for working CXX compiler: /opt/homebrew/Library/Homebrew/shims/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /opt/homebrew/bin/pkg-config (found version "0.29.2") 
-- Could NOT find LIBHACKRF (missing:  LIBHACKRF_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:17 (message):
  HackRF development files not found...


-- Configuring incomplete, errors occurred!
See also "/tmp/soapyhackrf-20170705-24501-605yom/SoapyHackRF-soapy-hackrf-0.3.1/build/CMakeFiles/CMakeOutput.log".
==> Kept temporary files
Temporary files retained at /tmp/soapyhackrf-20170705-24501-605yom

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/pothosware/homebrew-pothos/issues

rastapopoulos:~ russm$ 
```

CMakeOutput.log is attached (but doesn't appear useful)

[CMakeOutput.log.txt](https://github.com/pothosware/homebrew-pothos/files/1124727/CMakeOutput.log.txt)

As far as I can see, the error is coming out of FindLIBHACKRF.cmake which should be doing the right thing - it seems to be asking pkg-config how to build against libhackrf, and pkg-config knows:

```
rastapopoulos:~ russm$ pkg-config --cflags libhackrf
-I/opt/homebrew/Cellar/hackrf/2017.02.1/include/ -I/opt/homebrew/Cellar/libusb/1.0.21/include/libusb-1.0
rastapopoulos:~ russm$ pkg-config --libs libhackrf
-L/opt/homebrew/Cellar/hackrf/2017.02.1/lib -lhackrf
rastapopoulos:~ russm$ 
```

but I guess it's not actually using pkg-config and working (in the default layout) because homebrew defaults to just dumping everything in /usr/local ?

I tried building with `LIBHACKRF_INCLUDE_DIR` and `LIBHACKRF_LIBRARIES` explicitly set in the environment but that made no difference. (Does `brew install` sanitize the environment?)

**Comment by guruofquality** [comment]
can you try `brew link hackrf` I think the hackrf build through brew should have installed symlinks for the development files in /usr/local

**Comment by russm** [comment]
Ah, OK, the problem is hackrf's pkg-config info and SoapyHackRF/FindLIBHACKRF.cmake not agreeing on how to find the headers. Applying this patch to SoapyHackRF/FindLIBHACKRF.cmake fixes my homebrew issue and should help anyone else who's installing stuff in unusual locations. With this change you can probably also remove a bunch of the other PATHS entries in FIND_PATH(LIBHACKRF_INCLUDE_DIR) but better safe than sorry I guess?

```
diff --git a/FindLIBHACKRF.cmake b/FindLIBHACKRF.cmake-new
index a97fec5..34940ea 100644
--- a/FindLIBHACKRF.cmake
+++ b/FindLIBHACKRF.cmake-new
@@ -24,7 +24,7 @@ else (LIBHACKRF_INCLUDE_DIR AND LIBHACKRF_LIBRARIES)
 
   FIND_PATH(LIBHACKRF_INCLUDE_DIR
     NAMES hackrf.h
-    HINTS $ENV{LIBHACKRF_DIR}/include ${PC_LIBHACKRF_INCLUDEDIR}
+    HINTS $ENV{LIBHACKRF_DIR}/include ${PC_LIBHACKRF_INCLUDEDIR} ${PC_LIBHACKRF_INCLUDEDIR}/libhackrf
     PATHS /usr/local/include/libhackrf /usr/include/libhackrf /usr/local/include
     /usr/include ${CMAKE_SOURCE_DIR}/../libhackrf/src
     /opt/local/include/libhackrf
```

**Comment by guruofquality** [comment]
@russm It looks like the include should be <hackrf.h> and not <libhackrf/hackrf.h> so the pkt config is probably wrong and this should be a fix in hackrf. Perhaps the pc file was never being used correctly because of this and the explicit "PATHS" were always saving us here.

I think the patch is a good idea for now. But I thought that /usr/local/include/libhackrf should have a hackrf.h. Where did hackrf.h end up after running `brew link hackrf`. I know stuff actually gets installed into Cellar, but I expected brew to put symlinks in well known locations. Can you confirm?

@dominicgs looks like the hackrf pc file needs the libhackrf subdirectory:

```
diff --git a/host/libhackrf/libhackrf.pc.in b/host/libhackrf/libhackrf.pc.in                                                                                                                         
index 5c9c18d..3e1a983 100644                                                                                                                                                                        
--- a/host/libhackrf/libhackrf.pc.in                                                                                                                                                                 
+++ b/host/libhackrf/libhackrf.pc.in                                                                                                                                                                 
@@ -6,6 +6,6 @@ includedir=@includedir@                                                                                                                                                              
 Name: HackRF Library                                                                                                                                                                                
 Description: C Utility Library                                                                                                                                                                      
 Version: @VERSION@                                                                                                                                                                                  
-Cflags: -I${includedir}/ @HACKRF_PC_CFLAGS@                                                                                                                                                         
+Cflags: -I${includedir}/libhackrf @HACKRF_PC_CFLAGS@                                                                                                                                                
 Libs: -L${libdir} -lhackrf                                                                                                                                                                          
 Libs.private: @HACKRF_PC_LIBS@
```

**Comment by dominicgs** [comment]
I think this looks like the correct change to make, however I have one concern.  Existing software that uses libhackrf, e.g. SoapyHackRF and gr-osmosdr currently use `#include <libhackrf/hackrf.h>`.  Is it generally safe to assume that this will still succeed because `/usr/local/include/` is often included by default?

This works as expected on my Ubuntu system, but I know there are some differences with `/usr/local/lib/` on Arch systems, and I wonder if this applies to `/usr/local/include/`?

I have no knowledge of how other Unix like systems will handle this.

**Comment by guruofquality** [comment]
I guess it doesnt matter since there is existing code to support, but what is the intended use for API clients?
```
-I /usr/local/include
#include <libhackrf/hackrf.h>
```
or
```
-I /usr/local/include/libhackrf
#include <hackrf.h>
```
I guess I would change the PC file if this latter case is the intended one, but that could cause some issues for those that assumed libhackrf/hackrf.h

SoapyHackrf assumes <hackrf.h>, and wherever the FindLIBHACKRF.cmake in SoapyHackrf came from, it also assumed <hackrf.h>. Regardless, FindLIBHACKRF.cmake here wasnt using the PKG config file as it is now, but had enough other search paths to work fine.

Then gr-osmosdr uses <libhackrf/hackrf.h> and has its own FindLibHackRF.cmake which is using the pkg config hint as its implemented now.

> This works as expected on my Ubuntu system, but I know there are some differences with /usr/local/lib/ on Arch systems, and I wonder if this applies to /usr/local/include/?

The lib stuff varies a lot and depends on the ld library config/cache. The /usr/local/include/ is pretty much a default compiler search path.

----

PS You could always install project config files for hackrf so cmake clients can just use find_package(HackRF CONFIG) without the whole find script thing: https://cmake.org/Wiki/CMake/Tutorials/How_to_create_a_ProjectConfig.cmake_file :-)

**Comment by russm** [comment]
@guruofquality `brew link` returns `Warning: Already linked: /opt/homebrew/Cellar/hackrf/2017.02.1`. Note that this places symlinks to the Cellar files into the Homebrew prefix, not necessarily into /usr/local (though the prefix is usually /usr/local). So for me, brew link made these symlinks

```
rastapopoulos:homebrew russm$ ls -lF /opt/homebrew/include/libhackrf /opt/homebrew/lib/libhackrf.*
lrwxr-xr-x  1 hostadmin  wheel  44  5 Jul 22:14 /opt/homebrew/include/libhackrf@ -> ../Cellar/hackrf/2017.02.1/include/libhackrf
lrwxr-xr-x  1 hostadmin  wheel  52  5 Jul 22:14 /opt/homebrew/lib/libhackrf.0.5.0.dylib@ -> ../Cellar/hackrf/2017.02.1/lib/libhackrf.0.5.0.dylib
lrwxr-xr-x  1 hostadmin  wheel  48  5 Jul 22:14 /opt/homebrew/lib/libhackrf.0.dylib@ -> ../Cellar/hackrf/2017.02.1/lib/libhackrf.0.dylib
lrwxr-xr-x  1 hostadmin  wheel  42  5 Jul 22:14 /opt/homebrew/lib/libhackrf.a@ -> ../Cellar/hackrf/2017.02.1/lib/libhackrf.a
lrwxr-xr-x  1 hostadmin  wheel  46  5 Jul 22:14 /opt/homebrew/lib/libhackrf.dylib@ -> ../Cellar/hackrf/2017.02.1/lib/libhackrf.dylib
rastapopoulos:homebrew russm$ 
```

which obviously aren't anywhere in the default search paths so without a working pkg-config setup it's sad_trombone.wav

@dominicgs Looking at the `foo.pc` files on my Debian desktop, there's a bunch (eg: mpi, alsa, Qt5) where, presumably to support both `#include <foo/bar.h>` and `#include <bar.h>` forms, they just

```
Cflags: -I${includedir} -I${includedir}/foo
```

which seems a reasonable way to deal with whatever existing client code does.

**Comment by dominicgs** [comment]
I think we should assume that `<hackrf.h>` is the preferred method, and I'll go ahead and use the method that @russm suggested.

I'm going to add "Install project config files" to my todo list, because I'm not sure I have time in my schedule for it now, but I like the idea.

**Comment by guruofquality** [comment]
There's actually provisions to handle stuff like this: `PATH_SUFFIXES libhackrf`. And I dont know where all of these funny looking find cmake scripts come from in the first place. I guess they get copied around forever. I decided to rewrite the find script: https://github.com/pothosware/SoapyHackRF/commit/0ecfc4a21141ad7ef562689ca5ff66710edc8ed7

-- So this time around we let cmake handle the caching of variables, standard names for the hints, search all of the PC dirs provided. It hasnt let me down in the past, but I didnt test yet with a brew HEAD install. Should work with both the older and newer pc file as well.

I didnt care to keep the myriad of hardcoded search paths. Standard paths are already included, as well as the current CMAKE_INSTALL_PREFIX. For anyone with a custom prefix that is actually different between libhackrf and soapyhackrf, that can be fixed by either setting the PKG_CONFIG_PATH or passing in -DLIBHACKRF_INCLUDE_DIR and -DLIB_HACKRF_LIBRARY

**Comment by guruofquality** [comment]
Looks like this is basically resolved, obviously we need a new tag, but HEAD build should be fine for either hackrf pc file. Thanks!
